import type { LocationDetail } from "@/types";

// Single source of truth for all Pag-Asa Centre locations.
// Used by both the home page (`Locations.tsx`) and the about page (`AboutLocations.tsx`).
export const locations: LocationDetail[] = [
  {
    id: "dagenham",
    name: "Jo Richardson Community School, Dagenham",
    venue: "Jo Richardson Community School",
    address: "Castle Green, Gale St, Dagenham RM9 4UN",
    schedule: "Sunday | 02:00PM - 05:00PM",
    phone: "+44 79 8494 8682",
    email: "pagasa_media@hotmail.co.uk",
    imageUrl: "/loc-dagenham.jpg",
  },
  {
    id: "bray",
    name: "Bray, Ireland",
    venue: "Bray Methodist Church",
    address: "Florence Road, Bray, Ireland, A98 YR84",
    schedule: "Sunday | 12:00PM - 2:00PM",
    phone: "+353 87 186 4957",
    email: "pagasacentreirl@gmail.com",
    imageUrl: "/loc-bray.png",
  },
  {
    id: "pampanga",
    name: "Pampanga, Philippines",
    venue: "2nd Floor of Juliez Manukan Building",
    address: "San Matias Highway, Santo Tomas, Pampanga, Philippines",
    schedule: "Sunday | 8:30AM - 10:30AM",
    imageUrl: "/loc-pampanga.jpg",
  },
  {
    id: "bedfordshire",
    name: "Bedfordshire, UK",
    venue: "Bunyan Road Christian Centre",
    address: "30 Bunyan Road, Kempston, Bedfordshire, MK42 8HL",
    schedule: "Saturday | 3:00PM - 6:00PM (Every other week)",
    imageUrl: "/loc-bedfordshire.png",
  },
  {
    id: "reading",
    name: "Reading, UK",
    venue: "Emmanuel Church Centre",
    address: "South Lake Crescent, Woodley, Reading, RG5 3QW",
    schedule: "Saturday | 2:30PM - 5:00PM",
    imageUrl: "/loc-reading.jpg",
  },
  {
    id: "harwich",
    name: "Harwich, UK",
    venue: "Mayflower Primary School Hall",
    address: "Main Road, Dovercourt Harwich, Essex, C012 4AJ",
    schedule: "Saturday | 2:00PM - 4:00PM (Every other week)",
    imageUrl: "/loc-harwich.jpg",
  },
  {
    id: "banga",
    name: "Banga, South Cotabato, Philippines",
    venue: "Pag-Asa Centre Banga, Ruiz Compound",
    address: "Bgy Kusan, Barrio 8, Banga, South Cotabato, Philippines",
    schedule: "Sunday | 9:00AM - 11:00AM",
    imageUrl: "/loc-banga.jpg",
  },
  {
    id: "stratford",
    name: "Stratford Upon Avon, UK",
    venue: "Ken Kennett Centre",
    address: "100 Justins Avenue, CV37 0DA",
    schedule: "Sunday | 2:00PM - 6:00PM (Every other week)",
    imageUrl: "/loc-stratford.png",
  },
  {
    id: "westmidlands",
    name: "West Midlands & Worcestershire, UK",
    venue: "The Old Library Centre",
    address: "65 Ombersley Street East, Droitwich Spa, WR9 8QS",
    schedule: "Saturday | 2:00PM - 6:00PM (Every other week)",
    imageUrl: "/loc-droitwich.png",
  },
  {
    id: "southend",
    name: "Southend-on-Sea, UK",
    venue: "The Cornerstone URC Church",
    address: "Bournemouth Park Road, Essex, SS2 5JL",
    schedule: "Saturday | 2:30PM onwards",
    imageUrl: "/loc-south.png",
  },
];
